

# --------------------------------------------------------------------------
def fig_gulf_day(mode):
    """ONE GULF DAY, AND THE LIMIT NOBODY MEASURES.

    Reproduces the Simulink diurnal run from the Python core, so that the
    figure in the report is generated by the same code every other number in
    it comes from and cannot drift from the results.

    Three panels, and the third is the argument:

      1. Temperatures. The condenser skin runs well above anything the plant
         instruments see.
      2. The brucite saturation pH AT THE SKIN against the bulk pH the loop
         actually holds. It is retrograde, so it FALLS as the afternoon load
         pushes the skin hotter, and it crosses the operating point twice.
      3. What the plant's own two instruments read across the same day:
         conductivity and bulk pH, both flat.

    Note on panel 3: both traces are constant, which is the point. If each
    axis is centred on its own constant the two lines land on the same pixel
    row and one hides the other, which reads as a broken plot rather than as
    a result. The limits are therefore deliberately asymmetric.
    """
    import numpy as _np
    cal = json.loads((R / "calibration.json").read_text())
    fc, fn = cal["fill_c"], cal["fill_n"]

    import controller as ctl
    import chemistry as chem
    import run_controller as rc

    hour = _np.arange(24)
    s = _np.sin(_np.pi * _np.maximum(hour - 6, 0) / 16.0) ** 2
    T_db = 32.0 + 12.0 * s
    rh = 0.55 - 0.25 * s
    load = 0.62 + 0.38 * s

    CYCLES, BULK_PH, FAN_PCT, SKIN_DT = 4.0, 8.7, 85.0, 8.0
    w_loop = chem.balance_sodium(chem.ARAMCO_RECLAIMED)
    w_loop.SiO2 = 26.8
    conc = w_loop.concentrate(CYCLES)

    T_cold, T_hot, T_skin, pH_lim = [], [], [], []
    for i in range(len(hour)):
        cond = dict(rc.PLANT)
        cond.update({"T_db": float(T_db[i]), "rh": float(rh[i])})
        cond["Q_evap_kw"] = rc.PLANT["Q_evap_kw"] * float(load[i])
        th = ctl._thermal_solve(FAN_PCT, CYCLES, cond, rc.TSE, fc, fn)
        if th is None:
            T_cold.append(_np.nan); T_hot.append(_np.nan)
            T_skin.append(_np.nan); pH_lim.append(_np.nan)
            continue
        t_wo, t_wi = th[2], th[3]
        skin = t_wi + SKIN_DT
        T_cold.append(t_wo); T_hot.append(t_wi); T_skin.append(skin)
        pH_lim.append(chem.ph_saturation_brucite(skin, conc))

    T_cold = _np.array(T_cold); T_hot = _np.array(T_hot)
    T_skin = _np.array(T_skin); pH_lim = _np.array(pH_lim)
    depositing = pH_lim < BULK_PH
    hrs = int(_np.nansum(depositing))

    g = GEOM[mode]
    fig, axes = plt.subplots(3, 1, figsize=(g["figsize"][0], g["figsize"][1] * 1.55),
                             dpi=g["dpi"], sharex=True)
    base = g["base"]

    ax = axes[0]
    ax.plot(hour, T_skin, color=RED, lw=2.6, label="condenser tube skin - where scale forms")
    ax.plot(hour, T_hot, color=NAVY, lw=2.2, label="hot water leaving the condenser")
    ax.plot(hour, T_cold, color=TEAL, lw=2.2, label="cold water leaving the tower")
    ax.set_ylabel("temperature  [°C]", fontsize=base)
    ax.legend(loc="upper left", fontsize=base - 2.5, frameon=False)
    ax.grid(axis="y", alpha=0.20, ls=":"); ax.set_axisbelow(True)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)

    ax = axes[1]
    ax.plot(hour, pH_lim, color=RED, lw=2.6, label="scale limit, evaluated at the tube skin")
    ax.axhline(BULK_PH, color=GREY, lw=1.8, ls="--")
    ax.fill_between(hour, pH_lim, BULK_PH, where=depositing,
                    color=RED, alpha=0.13, interpolate=True)
    ax.text(0.4, BULK_PH + 0.012, "the loop actually runs here  (bulk pH %.1f)" % BULK_PH,
            fontsize=base - 2.5, color=GREY, weight="bold", va="bottom")
    ax.text(13.5, float(_np.nanmin(pH_lim)) + 0.03,
            "%d hours of 24 above the limit\nat the skin" % hrs,
            fontsize=base - 2.0, color=RED, weight="bold", ha="center",
            va="bottom", linespacing=1.5)
    ax.set_ylabel("pH", fontsize=base)
    ax.legend(loc="lower left", fontsize=base - 2.5, frameon=False)
    ax.grid(axis="y", alpha=0.20, ls=":"); ax.set_axisbelow(True)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)

    ax = axes[2]
    cond_uS = _np.full_like(hour, 1.55 * conc.TDS, dtype=float)
    c0 = float(cond_uS.mean())
    ax.plot(hour, cond_uS, color=TEAL, lw=2.6, label="conductivity")
    ax.set_ylabel("conductivity  [µS/cm]", fontsize=base, color=TEAL)
    ax.set_ylim(c0 * 0.94, c0 * 1.24)          # trace sits low in the frame
    ax.tick_params(axis="y", labelcolor=TEAL)
    ax2 = ax.twinx()
    ax2.plot(hour, _np.full_like(hour, BULK_PH, dtype=float),
             color=AMBER, lw=2.6, label="bulk pH")
    ax2.set_ylabel("bulk pH", fontsize=base, color=AMBER)
    ax2.set_ylim(BULK_PH - 0.80, BULK_PH + 0.20)   # trace sits high in the frame
    ax2.tick_params(axis="y", labelcolor=AMBER)
    ax2.spines["top"].set_visible(False)
    ax.text(12, c0 * 1.14, "both instruments read a flat line all day",
            fontsize=base - 1.5, color=GREY, weight="bold", ha="center")
    ax.set_xlabel("hour of the day", fontsize=base)
    ax.grid(axis="y", alpha=0.20, ls=":"); ax.set_axisbelow(True)
    for sp in ("top",):
        ax.spines[sp].set_visible(False)

    ax.set_xlim(0, 23)
    ax.set_xticks([0, 4, 8, 12, 16, 20])

    foot = ("Dhahran summer day: 32-44 °C dry bulb, cooling load 62-100 % of design, tower fan held at a fixed 85 %% as a building\n"
            "management system runs one today. Measured Saudi Aramco reclaimed water at 4 cycles with 26.8 mg/L silica; skin taken "
            "at bulk + %.0f K." % SKIN_DT)
    if mode == "report":
        fig.text(0.5, 0.015, foot, ha="center", fontsize=8.6, color=GREY, linespacing=1.6)
        fig.tight_layout(rect=[0, 0.055, 1, 1])
        out = FIGS / "gulf_day.png"
    else:
        fig.tight_layout()
        out = SLIDE / "gulf_day.png"
    fig.savefig(out, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print("   %-6s -> %s   (%d depositing hours)" % (mode, out.relative_to(ROOT), hrs))

