# Makefile generated by OpenModelica
# Platform: win64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang++ -shared -Xlinker --export-all-symbols
EXEEXT=.exe
DLLEXT=.dll
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS=-municode $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc/c" -I"C:/Program Files/OpenModelica1.27.0-64bit/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=silica -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS=-lSimulationRuntimeC -Wl,-Bdynamic -lomcgc -lryu -lopenblas -Wl,-B$(OMC_LDFLAGS_LINK_TYPE)  -lstdc++ -Wl,-Bdynamic 
LDFLAGS=-L"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/lib" -Wl,--stack,16777216,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib//omc" -L"C:/Program Files/OpenModelica1.27.0-64bit/bin" -Wl,-rpath,"C:/Program Files/OpenModelica1.27.0-64bit/lib"  -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lsz -Wl,-Bdynamic $(RUNTIME_LIBS) 
DIREXTRA=-L"C:/Users/Nouman/Desktop/Furqan's Docs/Startup/mizan/modelica"
MAINFILE=silica.c
MAINOBJ=silica.o
CFILES=silica_functions.c silica_records.c \
silica_01exo.c silica_02nls.c silica_03lsy.c silica_04set.c silica_05evt.c silica_06inz.c silica_07dly.c \
silica_08bnd.c silica_09alg.c silica_10asr.c silica_11mix.c silica_12jac.c silica_13opt.c silica_14lnz.c \
silica_15syn.c silica_16dae.c silica_17inl.c silica_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) silica.makefile silica_literals.h silica_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that silica_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) silica_functions.h silica_literals.h $(OFILES)
	$(CC) -I. -o silica$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) silica_functions.h silica_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o silica$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f silica_records.o $(MAINOBJ)

bundle:
	@tar -cvf silica_Files.tar $(GENERATEDFILES)