/* Additional record code for silica generated by the OpenModelica Compiler OpenModelica v1.27.0 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "silica_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

