/* Simulation code for TowerSilicaDynamics generated by the OpenModelica Compiler OpenModelica v1.27.0 (64-bit). */
#if !defined(silica__MODEL_H)
#define silica__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "silica_functions.h"


extern void silica_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void silica_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int silica_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int silica_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int silica_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int silica_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int silica_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int silica_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int silica_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int silica_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int silica_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int silica_checkForAsserts(DATA *data, threadData_t *threadData);
extern int silica_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int silica_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int silica_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* silica_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* silica_relationDescription(int i);
extern void silica_function_initSample(DATA *data, threadData_t *threadData);
extern int silica_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int silica_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int silica_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* silica_linear_model_frame(void);
extern const char* silica_linear_model_datarecovery_frame(void);
extern int silica_mayer(DATA* data, modelica_real** res, short *);
extern int silica_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int silica_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int silica_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int silica_setInputData(DATA *data, const modelica_boolean file);
extern int silica_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void silica_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void silica_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int silica_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void silica_read_simulation_info(SIMULATION_INFO* simulationData);
extern void silica_read_input_fmu(MODEL_DATA* modelData);
extern void silica_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int silica_inputNames(DATA* data, char ** names);
extern int silica_dataReconciliationInputNames(DATA* data, char ** names);
extern int silica_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int silica_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int silica_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int silica_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "silica_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(silica__MODEL_H) */


