%MIZAN_PINN  A physics-informed surrogate of the tower model, in MATLAB.
%
%   WHAT THIS IS, IN ONE PARAGRAPH
%
%   The physics model is exact but slow: working out what the tower will do
%   at one operating point takes about 140 milliseconds, and the controller
%   has to try hundreds of options before it picks one. This trains a small
%   neural network to give the same answer in about a microsecond, so the
%   controller can search properly instead of guessing coarsely.
%
%   WHY IT IS NOT JUST "AN AI MODEL"
%
%   A network trained only on data can say anything at all in a region
%   where there is no data. Our measurements come from a Spanish test rig
%   whose hottest humid day reaches 21.9 degC wet-bulb. ASHRAE 2025 gives
%   Dhahran a design wet-bulb of 30.5 degC at 1 %%, and an hourly TMY year
%   puts 40.5 %% of all hours above 21.9 degC. No amount of fitting closes
%   that gap, because there is nothing there to fit to.
%
%   A PHYSICS-INFORMED network can still be pinned down there. Alongside
%   the ordinary "match the data" term, the training adds a "obey physics"
%   term which is evaluated at points across the FULL Gulf range, including
%   the hot end where there is no data at all. It does not invent
%   measurements. It enforces four things thermodynamics guarantees
%   everywhere:
%
%       1. a wet cooling tower cannot cool water below the wet-bulb
%       2. more air cannot make the water hotter
%       3. hotter water in cannot make colder water out
%       4. the water coming out cannot be hotter than the water going in
%
%   Rules 2 and 3 are statements about SLOPES, which is what automatic
%   differentiation is for, and they are what stop the fitted surface doing
%   something absurd exactly where the product has to operate.
%
%   WHERE THE NETWORK IS NOT ALLOWED
%
%   Nowhere near the chemistry, and nowhere in the safety path. The
%   saturation limits that bound the controller are computed exactly, every
%   time. The surrogate proposes; the physics core disposes.
%
%   The gates below were fixed before the first training run, exactly as
%   every other gate in this package.
%
%   Requires: Deep Learning Toolbox.
%   Run:  mizan_pinn
clear; clc;
here = fileparts(mfilename('fullpath'));

% ---- gates, fixed before training -------------------------------------
GATE.core_Tout_MAE_K  = 0.10;   % faithfulness to the physics model
GATE.extrap_violations = 0;     % physical admissibility where there is no data
GATE.speedup_min       = 500;   % the speed that justifies the exercise

fprintf('%s\n', repmat('=', 1, 76));
fprintf('MIZAN :: physics-informed surrogate  --  gates fixed before training\n');
fprintf('%s\n', repmat('=', 1, 76));
fprintf('   faithfulness to the physics model, outlet temp MAE  <= %.2f K\n', GATE.core_Tout_MAE_K);
fprintf('   physical violations in the Gulf band, out of 4000     = %d\n', GATE.extrap_violations);
fprintf('   speed-up over the physics model                     >= %dx\n\n', GATE.speedup_min);

cal = jsondecode(fileread(fullfile(here, '..', 'results', 'calibration.json')));
fill_c = cal.fill_c;  fill_n = cal.fill_n;
fprintf('physics model: Me = %.4f (m_w/m_a)^(%.4f)\n', fill_c, fill_n);

% ---- training data, generated BY the physics model ---------------------
% The surrogate is trained against the model, not against the plant. It
% inherits every limitation the model has and adds its own; it is scored on
% how faithfully it reproduces the model, never on whether the model is
% right. That is what makes it a surrogate rather than a rival.
cache = fullfile(here, '..', 'results', 'matlab_pinn_labels.mat');
if isfile(cache)
    load(cache, 'X', 'Y');
    fprintf('reusing %d labelled points from %s\n', size(X,1), 'matlab_pinn_labels.mat');
else
    fprintf('labelling points from the physics model (a few minutes) ...\n');
    rng(20260830);
    N = 1400;  X = zeros(N,5); Y = zeros(N,1); k = 0; tries = 0;
    while k < N && tries < 8*N
        tries = tries + 1;
        T_db = 9 + 37*rand;  rh = 0.10 + 0.75*rand;
        m_w  = 1 + 3*rand;   m_a = 0.5 + 3*rand;
        T_wb = mizan.wetbulb_from_rh(T_db, rh);
        T_wi = T_wb + 4 + 18*rand;         % water is hotter than the wet bulb
        [t, info] = mizan.solve_outlet(T_wi, T_db, rh, m_w, m_a, fill_c, fill_n);
        if isempty(info) || ~isfinite(t), continue, end
        k = k + 1;
        X(k,:) = [T_db rh m_w m_a T_wi];  Y(k) = t;
    end
    X = X(1:k,:); Y = Y(1:k);
    save(cache, 'X', 'Y');
    fprintf('labelled %d points\n', k);
end

% wet-bulb at every training point, from the same psychrometrics
WB = arrayfun(@(i) mizan.wetbulb_from_rh(X(i,1), X(i,2)), (1:size(X,1))');

% split
rng(7); idx = randperm(size(X,1)); ntr = round(0.8*numel(idx));
tr = idx(1:ntr); te = idx(ntr+1:end);

mu = mean(X(tr,:), 1);  sd = std(X(tr,:), 0, 1) + 1e-9;
nrm = @(A) (A - mu)./sd;

% ---- collocation points: the Gulf band, with NO labels -----------------
% These carry no measurement and no model answer. They exist only so the
% physics term can be evaluated where the data does not reach.
rng(11); M = 900;
cT = 33 + 15*rand(M,1);  cR = 0.28 + 0.42*rand(M,1);
cWB = arrayfun(@(i) mizan.wetbulb_from_rh(cT(i), cR(i)), (1:M)');
cX = [cT cR 1+3*rand(M,1) 0.5+3*rand(M,1) cWB + 4 + 18*rand(M,1)];
fprintf('%d unlabelled collocation points at Gulf wet-bulbs\n\n', M);

% ---- the network -------------------------------------------------------
layers = [ featureInputLayer(5)
           fullyConnectedLayer(64)
           tanhLayer
           fullyConnectedLayer(64)
           tanhLayer
           fullyConnectedLayer(64)
           tanhLayer
           fullyConnectedLayer(1) ];
net = dlnetwork(layers);

Xtr = dlarray(single(nrm(X(tr,:)))', 'CB');
Ytr = dlarray(single(Y(tr))', 'CB');
Wtr = dlarray(single(WB(tr))', 'CB');
Xco = dlarray(single(nrm(cX))', 'CB');
Wco = dlarray(single(cWB)', 'CB');
Tin = dlarray(single(cX(:,5))', 'CB');

avgG = []; avgS = [];
fprintf('training ...\n');
for it = 1:2500
    [loss, grad] = dlfeval(@lossFcn, net, Xtr, Ytr, Wtr, Xco, Wco, Tin);
    [net, avgG, avgS] = adamupdate(net, grad, avgG, avgS, it, 3e-3);
    if mod(it, 500) == 0 || it == 1
        fprintf('   step %4d   loss %8.5f\n', it, double(gather(extractdata(loss))));
    end
end

% ---- score -------------------------------------------------------------
Xte = dlarray(single(nrm(X(te,:)))', 'CB');
Wte = dlarray(single(WB(te))', 'CB');
pred = double(gather(extractdata(fwd(net, Xte, Wte))))';
mae = mean(abs(pred - Y(te)));

% admissibility over 4000 fresh Gulf points
rng(99); V = 4000;
vT = 33 + 15*rand(V,1); vR = 0.28 + 0.42*rand(V,1);
vWB = arrayfun(@(i) mizan.wetbulb_from_rh(vT(i), vR(i)), (1:V)');
vX = [vT vR 1+3*rand(V,1) 0.5+3*rand(V,1) vWB + 4 + 18*rand(V,1)];
Xv = dlarray(single(nrm(vX))', 'CB');
Wv = dlarray(single(vWB)', 'CB');
[Tv, g] = dlfeval(@predAndGrad, net, Xv, Wv);
Tv = double(gather(extractdata(Tv)))';
g  = double(gather(extractdata(g)));
v_wb   = sum(Tv < vWB - 1e-6);
v_ma   = sum(g(4,:) > 1e-6);
v_twi  = sum(g(5,:) < -1e-6);
v_cool = sum(Tv > vX(:,5) + 1e-6);
viol = v_wb + v_ma + v_twi + v_cool;

% speed
ns = 60; rng(5);
sT = 33 + 12*rand(ns,1); sR = 0.3 + 0.4*rand(ns,1);
sWB = arrayfun(@(i) mizan.wetbulb_from_rh(sT(i), sR(i)), (1:ns)');
sX = [sT sR 1+3*rand(ns,1) 0.5+3*rand(ns,1) sWB + 6 + 12*rand(ns,1)];
t0 = tic;
for i = 1:ns
    mizan.solve_outlet(sX(i,5), sX(i,1), sX(i,2), sX(i,3), sX(i,4), fill_c, fill_n);
end
t_core = toc(t0)/ns;
Xs = dlarray(single(nrm(sX))', 'CB'); Ws = dlarray(single(sWB)', 'CB');
t0 = tic; for r = 1:200, fwd(net, Xs, Ws); end
t_net = toc(t0)/(200*ns);
speedup = t_core/t_net;

fprintf('\n%s\n', repmat('=', 1, 76));
fprintf('PINN GATES -- scored once, against thresholds fixed before training\n');
fprintf('%s\n', repmat('=', 1, 76));
pr = @(ok) subsref({'FAIL','PASS'}, substruct('{}', {ok+1}));
fprintf('  faithfulness to the physics model, MAE  %10.4f K   limit %6.2f   %s\n', ...
        mae, GATE.core_Tout_MAE_K, pr(mae <= GATE.core_Tout_MAE_K));
fprintf('  physical violations, Gulf band          %10d     limit %6d   %s\n', ...
        viol, GATE.extrap_violations, pr(viol <= GATE.extrap_violations));
fprintf('  speed-up over the physics model         %10.0fx    limit %6dx  %s\n', ...
        speedup, GATE.speedup_min, pr(speedup >= GATE.speedup_min));
fprintf('\n  breakdown: below wet-bulb %d, more-air-warms-water %d,\n', v_wb, v_ma);
fprintf('             hotter-in-colder-out %d, outlet above inlet %d\n', v_twi, v_cool);
fprintf('  physics model %.1f ms per point, surrogate %.2f us per point\n', ...
        1e3*t_core, 1e6*t_net);

out = struct('Tout_MAE_K', mae, 'violations', viol, 'speedup', speedup, ...
             'core_ms', 1e3*t_core, 'net_us', 1e6*t_net, ...
             'n_train', numel(tr), 'n_collocation', M);
fid = fopen(fullfile(here, '..', 'results', 'matlab_pinn.json'), 'w');
fprintf(fid, '%s', jsonencode(out, 'PrettyPrint', true)); fclose(fid);
fprintf('\nwritten -> results/matlab_pinn.json\n');


% =======================================================================
function T = fwd(net, Xn, wb)
%FWD  Outlet temperature = wet-bulb + a strictly positive approach.
%   The "cannot cool below the wet bulb" rule is built into the ARCHITECTURE
%   rather than punished in the loss. A hard physical bound belongs in the
%   structure of the model; only the soft ones belong in the training.
    T = wb + softplus(forward(net, Xn));
end

function y = softplus(x)
    % numerically stable log(1+exp(x)); log1p does not accept a dlarray
    y = log(1 + exp(-abs(x))) + max(x, 0);
end

function [T, g] = predAndGrad(net, Xn, wb)
    T = fwd(net, Xn, wb);
    g = dlgradient(sum(T, 'all'), Xn);
end

function [loss, grad] = lossFcn(net, Xtr, Ytr, Wtr, Xco, Wco, Tin)
    % 1. match the physics model where we have its answer
    Tp = fwd(net, Xtr, Wtr);
    loss = mean((Tp - Ytr).^2, 'all');

    % 2. obey physics where we do not -- at Gulf collocation points
    Tc = fwd(net, Xco, Wco);
    g  = dlgradient(sum(Tc, 'all'), Xco, 'EnableHigherDerivatives', true);
    dma  = g(4,:);      % more air must not warm the water
    dtwi = g(5,:);      % hotter inlet must not cool the outlet
    loss = loss ...
         + 60*mean(max(dma, 0).^2, 'all') ...
         + 60*mean(max(-dtwi, 0).^2, 'all') ...
         + 20*mean(max(Tc - Tin, 0).^2, 'all');   % outlet cannot exceed inlet

    grad = dlgradient(loss, net.Learnables);
end
